---
title: "ESM 244 Lab 1"
author: "Alex Ehrens"
date: "1/7/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(tidyverse)
library(here)
library(sf)
library(tmap)
```

### Read in SF trees data

```{r}
sf_trees <- read_csv(here("data", "sf_trees", "sf_trees.csv"))
```

### Basic wrangling reminders

Refresh some skills for data wrangling and summary statistics using functions in the `dplyr` package.

Find the top 5 highest observations of trees by legal_status, do some wrangling, make a graph.

```{r}
top_5_status <- sf_trees %>% 
  count(legal_status) %>% # count function does all of what group_by, summarize, n() functions do
# can set multiple group levels in same place (count(legal_status, species))
  drop_na(legal_status) %>% # gets rid of rows all NA values in certain variable
  rename(tree_count = n) %>% # new name on left, old name on right
  relocate(tree_count) %>% # moves tree_count to first column position 
  slice_max(tree_count, n = 5) # only leaves top 5 highest values of tree_count
```

